# Generated by Django 2.0.2 on 2018-04-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reggistration_form',
            new_name='reggistration_model',
        ),
    ]
